markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

repository: bcgov/MyGovBC-notification-server

collections:
  docs:
    output: true

name: NotifyBC
title: NotifyBC
description: A versatile notification API server
baseurl: "/MyGovBC-notification-server"
url: "https://bcgov.github.io"

logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
